lib/utils/utils.dart
lib/widgets/sliders/aircraft/detail/location_fields.dart
lib/widgets/sliders/aircraft/detail/operator_fields.dart

In aircraft detail, invalid values for area floor/ceil, vert/hori speed were still not detected.
There was also a bug in lib in parsing these values, solved by commit [1](https://github.com/dronetag/flutter-opendroneid/commit/d2a9a17e96b80aad175817bed682aaf513430477) and [2](https://github.com/dronetag/flutter-opendroneid/commit/9a0d998f12bca1856e86bedcc53c8c0873ba8810)

Fix aircraft detail

---

lib/bloc/opendroneid_cubit.dart
lib/widgets/toolbars/components/scanning_state_icons.dart
pubspec.lock
pubspec.yaml

Solve cases when Bt/Wi-Fi is turned off. Check if Wi-Fi is available before starting scans.
Depending on the phone settings, we can scan even with Wi-Fi turned off.
Uses updated API of flutter-opendroneid, depends on [PR 4](https://github.com/dronetag/flutter-opendroneid/pull/4)

Fix: handling scanning state

---

lib/widgets/app/dialogs.dart

The elevation of snackbar used so far was nonsensically high, it probably caused high memory consumption.

Use default snackbar elevation

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist

The permission allows to interact with all installed apps. We need to interact just with the web browser, so I added <queries> element instead with intent to open web pages.
Also adds related LSApplicationQueriesSchemes entry to info.plist, as recommended in url_launcher package readme.

Remove query_all_packages permission from Android manifest

---

lib/bloc/map/map_cubit.dart
lib/widgets/mainpage/map_ui_google.dart
lib/widgets/preferences/preferences_page.dart
lib/widgets/sliders/aircraft/aircraft_actions.dart
lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
lib/widgets/sliders/common/airspace_list.dart
lib/widgets/toolbars/map_options_toolbar.dart

Disable option to follow aircraft if its location is not valid. Turn of lock if other aircraft is selected or selected is deleted.

Fix: disable lock on unknown location

---

lib/constants/sizes.dart
lib/widgets/sliders/aircraft/aircraft_card.dart
lib/widgets/sliders/aircraft/aircraft_card_title.dart
lib/widgets/sliders/aircraft/detail/location_fields.dart
lib/widgets/sliders/aircraft/detail/operator_fields.dart
lib/widgets/sliders/common/airspace_list.dart

Handle cases with unknown values for all possible fields of remote id messages, e.g. do not show grounded/airborne aircraft icons in card/detail when status is unknown.

Fix: unknown values in messages from aircraft

---

lib/bloc/aircraft/aircraft_cubit.dart
lib/bloc/map/map_cubit.dart
lib/bloc/opendroneid_cubit.dart

Change algorithm that filters out points from trajectory when max number of points is reached. Change debouncing time and set max points in trajectory to 400. The number was worked out experimentally, so map does not lag when trajectory is shown on oldest possible phones.

Fix: map trajectories

---

ios/Runner/Info.plist

Set scheme to be able to open the app from another app on iOS.

feat: Add `dronescanner` scheme

---

ios/Runner/Info.plist

Set URL name, role and scheme in  `CFBundleURLTypes` element in in _Info.plist_. I set up opening from other apps according to [this post](https://stackoverflow.com/a/59648933).

Feature: define url scheme on ios

---

android/app/src/main/AndroidManifest.xml
lib/bloc/aircraft/aircraft_cubit.dart

Because target android SDK changed to 33, we need to use video and photo permission for storing files on a device.
Tested on Android 9 (API 28), Android 13 (API 33) and iOS 16.

fix: android storage permission

---

android/app/src/main/AndroidManifest.xml
lib/bloc/showcase_cubit.dart
lib/bloc/showcase_state.dart
lib/widgets/app/app.dart
lib/widgets/app/dialogs.dart
lib/widgets/app/life_cycle_manager.dart
lib/widgets/mainpage/home_body.dart

Add a dialog explaining why we need location permission for BT scanning.
We found out that we need users to select "while using the app" option when they are asked for location permission so background scan would work. Moreover, location will be required by the library after ([PR18](https://github.com/dronetag/flutter-opendroneid/pull/18)). More explanation is in [Jira issue](https://dronetag.atlassian.net/browse/DT-2407) comments.
The new dialog is shown before every location request. When user denies location once, system request is then not shown. Unfortunately, we cannot say if user already denied the permission, so dialog is shown every time and If user already dismissed the permission, he can go to app settings using the button.
On the first app start, show all the permission …

Feature: background tasks, location permission explanation

---

lib/main.dart

Remove `runZonedGuarded`, Sentry captures errors automatically.

feat: remove use of Zone 

---

android/build.gradle
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.lock
pubspec.yaml

Upgrade packages that were preventing build with newer Flutter versions.
Bumping google maps also solves the issue with ghost markers and trajectories that remained on the map.
Bump flutter-opendroneid to 0.13.0.

Chore: upgrade outdated packages

---

lib/bloc/help/help_cubit.dart
lib/widgets/preferences/proximity_alerts_page.dart

Help question about the Drone Radar feature was finally added to help, point a link from Drone Radar page to it.

feat: open correct question in help when navigating from DroneRadar

---

.github/workflows/delivery.yml
pubspec.lock
pubspec.yaml

This should add the debug symbols to the project release on sentry. I was not able to test it, since the master branch here is protected and the workflow for the toolbox project is not working for quite some time now so I was not able to test it there either. I successfully tried with my own sentry auth token that the setting in the `pubspec.yaml` file is working and the files are being uploaded. This was done according to the commit in the app project and according to the documentation from sentry.
`dart run sentry_dart_plugin` was added to the workflow together with specified  `SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}` environment variable, which should be taken from the organisational setup.

Debug symbols (DT-2720)

---

lib/bloc/aircraft/aircraft_cubit.dart
lib/bloc/aircraft/export_cubit.dart
lib/main.dart
lib/utils/gpxlogger.dart
lib/widgets/preferences/preferences_page.dart
lib/widgets/sliders/aircraft/aircraft_actions.dart

Move export functionality from `AircraftCubit` to newly created `ExportCubit`.
Add option to export GPX, which is XML with coordinates and can be imported to various map services.
GPX exported from the app to _mapy.cz_:
Solves the issue https://github.com/dronetag/drone-scanner/issues/64.
DT-2868

Add GPX export format support

---

.github/workflows/delivery.yml
.github/workflows/integration.yml
ios/Flutter/AppFrameworkInfo.plist
ios/Podfile
ios/Podfile.lock
lib/constants/theme.dart
lib/widgets/app/custom_about_dialog.dart
lib/widgets/help/help_page.dart
lib/widgets/preferences/components/custom_dropdown_button.dart
lib/widgets/preferences/components/preferences_field_with_description.dart
lib/widgets/preferences/components/proximity_alert_distance_field.dart
lib/widgets/preferences/preferences_page.dart
lib/widgets/preferences/proximity_alerts_page.dart
lib/widgets/showcase/showcase_start_widget.dart
lib/widgets/sliders/aircraft/aircraft_card.dart
lib/widgets/sliders/aircraft/aircraft_card_custom_text.dart
lib/widgets/sliders/common/num_drones_text.dart
lib/widgets/sliders/common/refreshing_text.dart
lib/widgets/sliders/zones/zone_detail.dart
lib/widgets/toolbars/toolbar.dart
pubspec.lock
pubspec.yaml

Update flutter to 3.16. I mostly mimicked what was done in other repos.
I also solved the issue with `textScaleFactor` being deprecated. There is also another deprecation of `WillPopScope` that does not seem so trivial so I created an issue for it: [DT-2953](https://dronetag.atlassian.net/browse/DT-2953)
[DT-2953]: https://dronetag.atlassian.net/browse/DT-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: update flutter to 3.16

---

lib/bloc/aircraft/aircraft_cubit.dart
lib/services/ornithology_rest_client.dart

App did not handle cases when ornithology did not recognize the aircraft and returned `404 - Aircraft not found`. If this happened, the progress indicators on aircraft detail kept spinning. This can be seen e.g. with Japanese devices.
Return `null` from ornithology client when aircraft is not found.

fix: handle ornithology service not recognizing aircraft

---

lib/bloc/aircraft/aircraft_cubit.dart
lib/bloc/aircraft/aircraft_state.dart
lib/bloc/aircraft/export_cubit.dart
lib/bloc/map/map_cubit.dart
lib/bloc/proximity_alerts_cubit.dart
lib/utils/csvlogger.dart
lib/widgets/preferences/components/users_device_uas_id_text_field.dart
lib/widgets/sliders/aircraft/aircraft_actions.dart
lib/widgets/sliders/aircraft/aircraft_card.dart
lib/widgets/sliders/aircraft/detail/aircraft_detail.dart
lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
lib/widgets/sliders/aircraft/detail/basic_fields.dart
lib/widgets/sliders/aircraft/detail/set_as_mine_button.dart
lib/widgets/sliders/common/headline.dart
pubspec.lock
pubspec.yaml

Handle multiple basic id messages with different types of UAS ID.
Show multiple UAS IDs in aircraft detail. In other places like card, map, proximity alerts show preferred UAS ID, which is of `SerialNumber` type if such id exists.
Depends on https://github.com/dronetag/flutter-opendroneid/pull/28.
DT-2987

feat: handle multiple basic id messages

---

.github/workflows/delivery.yml

In our delivery workflow we used [macos-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md). It has Xcode 14.2 and iOS SDK 16.2 installed.
Switch to [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md) which has Xcode 15.0.1 and iOS SDK 17.2.
Also changed in https://github.com/dronetag/app/pull/362 and https://github.com/dronetag/toolbox/pull/65.
DT-3007

chore: bump macos version in delivery workflow

---

lib/bloc/map/map_cubit.dart
lib/bloc/sliders_cubit.dart
lib/widgets/app/proximity_alert_snackbar.dart
lib/widgets/mainpage/home_page.dart
lib/widgets/sliders/aircraft/aircraft_actions.dart
lib/widgets/sliders/airspace_sliding_panel.dart
lib/widgets/sliders/common/airspace_list_header.dart
lib/widgets/sliders/sheet/sheet.dart
lib/widgets/toolbars/components/location_search.dart

Due to `WillPopScope` deprecation the widget code was migrated to the new `PopScope` widget which supports new Android predictive back.
Refactored `isPanelClosed()` and `isPanelOpened()` into getters.

Migrated from `WillPopScope` to `PopScope`

---

.github/workflows/delivery.yml
.github/workflows/integration.yml
android/app/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
ios/Podfile.lock
lib/widgets/mainpage/map_ui_google.dart
lib/widgets/showcase/showcase_item.dart
lib/widgets/showcase/showcase_root.dart
pubspec.lock
pubspec.yaml

Upgrade flutter to 3.22
Upgrade packages and fix breaking changes. 
Showcaseview is not yet compatible on master so I used commit which fixes it from it's repo. I also had to upgrade flutter_spinbox, wakelock, package_info_plus. Then there were issues with Java and gradle compatibility, which I solved by installing the newest Android studio and bumping compileSdk in build.gradle.

chore: upgrade flutter to 3.22

---

android/app/build.gradle

As Lukas [reported on slack](https://getdronetag.slack.com/archives/C02N11D6D5J/p1716997963316389), the app crashed on startup on Pixel 8 with Android 14.
Fix crash by adding _WindowManager_ dependency to _build.gradle._
Crash was actually caused by `flutter_local_notifications` package or as they claim it's a Flutter [issue](https://github.com/flutter/flutter/issues/110658). I found the fix in package's [readme](https://pub.dev/packages/flutter_local_notifications#-android-setup).
Tested app startup on virtual pixel 8 with sdk lvl 34. I also sent the app to lukas to see if it fixed the issue on a real device.

fix: app crashing on pixel 8 with android 14 

---

lib/bloc/aircraft/aircraft_cubit.dart
lib/bloc/aircraft/aircraft_metadata_cubit.dart
lib/exceptions/invalid_country_code_exception.dart
lib/main.dart
lib/models/message_container_authenticity_status.dart
lib/services/location_service.dart
lib/utils/message_container_authenticator.dart
lib/widgets/sliders/aircraft/aircraft_card.dart
lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
lib/widgets/sliders/common/flag.dart

Add 2 new detectors: `LocationTimestampSpooferDetector` and `LocationSpooferDetector`. Show all data authenticity statuses in app UI.
`LocationSpooferDetector` compares phone location with the aircraft location and returns spoofed probability based on distance. If the distance is 3000-10000 meters, data are considered suspicious (probability of being spoofed is 0.75). If the distance is bigger than 10000 meters, data are considered counterfeit (probability 1). Since the spoofer has configurable location, it is possible that data are spoofed even when distance to phone is smaller.
`LocationTimestampSpooferDetector` compares timestamp from location message with the system time.  I used bit more strict thresholds than were written in the task. If the difference is btw 10-60 seconds, data are …

feat: positive spoofer detectors

---

lib/bloc/units_settings_cubit.dart
lib/bloc/units_settings_state.dart
lib/constants/theme.dart
lib/constants/theme_buttons.dart
lib/widgets/app/custom_about_dialog.dart
lib/widgets/app/life_cycle_manager.dart
lib/widgets/help/help_page.dart
lib/widgets/mainpage/map_ui_google.dart
lib/widgets/preferences/components/preferences_slider.dart
lib/widgets/preferences/components/screen_sleep_checkbox.dart
lib/widgets/preferences/preferences_page.dart
lib/widgets/preferences/proximity_alerts_page.dart
lib/widgets/showcase/showcase_start_widget.dart
lib/widgets/showcase/showcase_widget.dart
lib/widgets/sliders/aircraft/detail/set_as_mine_button.dart

Flutter 3.22 brings a new batch of lints and deprecations.
Lints:
- `Don't use 'BuildContext's across async gaps, guarded by an unrelated 'mounted' check` [use_build_context_synchronously](https://dart.dev/tools/linter-rules/use_build_context_synchronously).
This one is quite useful, we spammed `context.mounted` checks everywhere, but in stateful widget, `state.mounted` property should be checked instead
Deprecations:
- [Rename MaterialStateProperty to WidgetStateProperty](https://docs.flutter.dev/release/breaking-changes/material-state).
`MaterialState`, and its related APIs, have been moved out of the Material library and renamed to `WidgetState`.
- [new ColorScheme roles](https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles).
`background` should be replaced with …

chore: flutter 3.22 deprecations and lints

---

ios/Runner/Info.plist
lib/bloc/standards_cubit.dart
lib/widgets/app/dialogs.dart
lib/widgets/app/life_cycle_manager.dart
lib/widgets/preferences/preferences_page.dart

Add dialog about why background location is needed and request `locationAlways` permission. Background location is required for drone radar to work while the app is in the background.
Location permission should be requested gradually. First `location`, then if is enabled, request `locationAlways`.
On Android, there is no system dialog where the user can enable background location. The user has to select it in the app settings. Requesting `locationAlways` using permission handler navigates the user to settings. I added a dialog that explains why `locationAlways` is needed, selecting _'Continue'_ navigates to app settings.
This should be compliant with a [guide](https://developer.android.com/develop/sensors-and-location/location/permissions#background-dialog-target-android-11) on how to …

feat: request background location permission

---

ios/Podfile.lock
lib/bloc/proximity_alerts_cubit.dart
lib/services/notification_service.dart
lib/widgets/app/life_cycle_manager.dart
pubspec.lock
pubspec.yaml

Sending local notifications when app is in background failed with:
`PlatformException (PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted))` on Android 14.
Bump [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) package and use method `show()` instead of `zonedSchedule()` which requires `android.permission.USE_EXACT_ALARM`

fix: local notifications on Android

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

Bump sentry and url_launcher packages to be able to build for iOS 18.

chore: ios 18 support

---

lib/utils/csvlogger.dart

Add location timestamp to CSV export. Previously, there was just received time all messages. Rename this column to _"Received Timestamp"_ and add _"Location Timestamp"_ .
I kept it in original format: elapsed duration from start of last full hour. We could add last full hour to create complete timestamp but result may be wrong if eg. duration is 59 m 59s and packet is received at the next hour.

feat: add location timestamp to export

---

.github/workflows/delivery.yml

Add missing upload of assets to Github release to delivery workflow.
Solves https://github.com/dronetag/drone-scanner/issues/77.
DT-3177

ci: add asset upload to delivery
