dronetag/drone-scanner

- lib/bloc/screen_cubit.dart
- lib/widgets/mainpage/home_body.dart
Problem was with storing the screen size to soon in main file, when the app was not initialized.
> fix: solve broken ui design in release mode

- lib/utils/utils.dart
- lib/widgets/sliders/aircraft/aircraft_card.dart
- lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
- lib/widgets/sliders/aircraft/detail/operator_fields.dart
This resolves range errors  in sentry issues 3, 4, 5.
> Fix unchecked operator id length when reading country code

- lib/bloc/aircraft/aircraft_cubit.dart
- lib/bloc/map/map_cubit.dart
- lib/bloc/opendroneid_cubit.dart
- lib/utils/csvlogger.dart
- lib/utils/utils.dart
- lib/widgets/app/life_cycle_manager.dart
- lib/widgets/mainpage/home_body.dart
- lib/widgets/mainpage/map_ui_google.dart
- pubspec.lock
- pubspec.yaml
Noticeably improves performance. Map objects are now redrawn 2 times a second, not on every update. 
Map does not lag when moving camera.
There are related changes library, e.g. deduplication of messages.
> Feature: Performance Optimizations

- lib/bloc/aircraft/aircraft_cubit.dart
- lib/bloc/map/map_cubit.dart
- lib/bloc/opendroneid_cubit.dart
- lib/utils/utils.dart
- lib/widgets/preferences/components/custom_spinbox.dart
- lib/widgets/preferences/components/preferences_field.dart
- lib/widgets/sliders/aircraft/aircraft_actions.dart
- lib/widgets/sliders/aircraft/aircraft_card.dart
- lib/widgets/sliders/aircraft/aircraft_card_custom_text.dart
- lib/widgets/sliders/aircraft/detail/location_fields.dart
- lib/widgets/sliders/aircraft/detail/operator_fields.dart
- lib/widgets/sliders/common/airspace_list.dart
- pubspec.lock
- pubspec.yaml
Check for invalid loc values (0,0), fix heading track indicator and op altitude
> Fix  bugs in ui

- lib/bloc/screen_cubit.dart
- lib/widgets/mainpage/home_body.dart
- lib/widgets/preferences/components/screen_sleep_checkbox.dart
- lib/widgets/preferences/preferences_page.dart
- pubspec.lock
- pubspec.yaml
user can disable screen sleep in preferences
> feature: use wakelock package to prevent screen sleep

- lib/widgets/mainpage/home_page.dart
close drone detail or animate panel to snap point on tap
> feature: use back button on android

- lib/bloc/aircraft/aircraft_cubit.dart
Data buffer was not correctly cleared.
> fix: clearing gathered aircraft data

- lib/utils/utils.dart
- lib/widgets/mainpage/home_body.dart
- lib/widgets/preferences/components/custom_spinbox.dart
- lib/widgets/preferences/preferences_page.dart
- lib/widgets/sliders/aircraft/aircraft_card_custom_text.dart
- lib/widgets/sliders/aircraft/aircraft_card_title.dart
- lib/widgets/sliders/aircraft/detail/aircraft_detail.dart
- lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
- lib/widgets/sliders/aircraft/detail/aircraft_label_text.dart
- lib/widgets/sliders/aircraft/detail/location_fields.dart
- lib/widgets/sliders/aircraft/detail/operator_fields.dart
- lib/widgets/sliders/common/airspace_list.dart
- lib/widgets/sliders/common/airspace_list_header.dart
- lib/widgets/sliders/zones/zone_detail.dart
- lib/widgets/toolbars/map_options_toolbar.dart
Make slider in collapsed state bigger, fix combobox in preferences to set time after which data are cleared.
Do not show distance of aircraft or operator when user location is not valid.
> Minor UI improvements and tweaks

- lib/widgets/sliders/aircraft/detail/location_fields.dart
- lib/widgets/sliders/aircraft/detail/operator_fields.dart
In operator section, change label altitude to altitude geod.
> fix: change labels in detail

- lib/bloc/aircraft/aircraft_cubit.dart
- lib/constants/sizes.dart
- lib/extensions/string_extensions.dart
- lib/utils/utils.dart
- lib/widgets/sliders/aircraft/aircraft_card.dart
- lib/widgets/sliders/aircraft/detail/aircraft_detail.dart
- lib/widgets/sliders/aircraft/detail/aircraft_detail_header.dart
- lib/widgets/sliders/aircraft/detail/operator_fields.dart
Show warning if operator id does not have correct length or contains non-alphanumeric characters.
> Feature: check operator id validity

- lib/bloc/opendroneid_cubit.dart
- lib/widgets/preferences/preferences_page.dart
Add option to set scan priority to preferences.
Depends on [PR10](https://github.com/dronetag/flutter-opendroneid/pull/10)
> Feature: bt scan priority

- lib/bloc/opendroneid_cubit.dart
- lib/bloc/showcase_cubit.dart
- lib/constants/snackbar_messages.dart
- lib/widgets/app/life_cycle_manager.dart
- lib/widgets/preferences/components/scanning_status_field.dart
- lib/widgets/toolbars/components/scanning_state_icons.dart
- lib/widgets/toolbars/components/toolbar_actions.dart
- pubspec.lock
- pubspec.yaml
Refresh permissions statuses after user returns to app.
Do not allow starting scans without location permission on Android. Notify user using snackbars.
> Feature: permissions handling

- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/bloc/standards_cubit.dart
- lib/widgets/toolbars/components/location_search.dart
- lib/widgets/toolbars/toolbar.dart
- pubspec.lock
- pubspec.yaml
Remove places autocomplete by google. Add Autocomplete widget that gives suggestion using openstreetmap.
Requires version of flutter-opendroneid with updated dependencies.
> Feature: replace google autocomplete

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
Update Android SDK version and gradle version.
> Fix: android config

- lib/bloc/aircraft/aircraft_cubit.dart
- lib/utils/csvlogger.dart
- lib/widgets/preferences/preferences_page.dart
- lib/widgets/sliders/aircraft/aircraft_actions.dart
- pubspec.lock
- pubspec.yaml
Fix exported CSV file format, use 1 common header on 1st row. Rename exported files. Fix timestamp.
Replace deprecated share method and show snackbar if exported successfully.
> Fix: CSV exports

- .github/workflows/delivery.yml
- .github/workflows/integration.yml
- android/build.gradle
- ios/Podfile.lock
- lib/utils/utils.dart
- lib/widgets/sliders/aircraft/aircraft_card.dart
- lib/widgets/sliders/aircraft/detail/connection_fields.dart
- pubspec.lock
- pubspec.yaml
Ensure compatibility with Flutter 3.10
> Feature: upgrade Flutter to 3.10

- analysis_options.yaml
- lib/bloc/aircraft/aircraft_cubit.dart
- lib/bloc/aircraft/aircraft_expiration_cubit.dart
- lib/bloc/help/help_cubit.dart
- lib/bloc/proximity_alerts_cubit.dart
- lib/bloc/screen_cubit.dart
- lib/constants/theme.dart
- lib/constants/theme_buttons.dart
- lib/services/notification_service.dart
- lib/widgets/app/proximity_alert_snackbar.dart
- lib/widgets/mainpage/home_body.dart
- lib/widgets/preferences/components/preferences_slider.dart
- lib/widgets/preferences/components/scanning_status_field.dart
- lib/widgets/preferences/components/users_device_uas_id_text_field.dart
- lib/widgets/preferences/preferences_page.dart
- lib/widgets/preferences/proximity_alerts_page.dart
- lib/widgets/sliders/aircraft/aircraft_card.dart
- lib/widgets/sliders/airspace_sliding_panel.dart
- lib/widgets/sliders/sheet/scrolling.dart
replace deprecated members, remove unused properties, make some code lines shorter
> chore: solve code analysis issues

- lib/widgets/sliders/aircraft/detail/basic_fields.dart
Fix snackbars that are displayed after setting aircraft as owned from aircraft detail.
> fix: drone radar snackbars 

- ios/Podfile.lock
- lib/widgets/preferences/preferences_page.dart
- pubspec.lock
- pubspec.yaml
Bump app_settings package to 5.1.1, no other changes were required.
DT-2748
> chore: bump app_settings package

- ios/Podfile.lock
- lib/bloc/aircraft/aircraft_cubit.dart
- lib/bloc/geocoding_cubit.dart
- lib/bloc/standards_cubit.dart
- lib/main.dart
- lib/models/place_details.dart
- lib/services/geocoding_rest_client.dart
- lib/widgets/toolbars/components/location_search.dart
- pubspec.lock
- pubspec.yaml
In this PR I originally wanted to solve [DT-2777](https://dronetag.atlassian.net/browse/DT-2777) by updating `osm_flutter_plugin` and `permission_handler` package versions to sync with other repos and to be able to bump `flutter-opendroneid`.
After dealing with few conflicts and finding out that the newest `osm_flutter_plugin` is still not compatible, I decided to remove `osm_flutter_plugin` package and use own client to Nominatim API, similar to what we have in the app. So to sum up, I removed `osm_flutter_plugin` and unused `flogs` and bumped  `permission_handler`, `flutter-opendroneid` and `sprintf`.
I created `NominatimGeocodingRestClient ` that returns list of `PlaceDetails` for given query. I also changed the UI of location search a bit - I added button to clear current query and …
> chore: clean up packages, replace osm plugin
